---
# tasks file for update

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes

- name: Configure APT
  block:
    - name: Update all software (APT)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: "{{ update_upgrade_command }}"

    - name: apt autoremove (APT)
      ansible.builtin.apt:
        autoremove: "{{ update_autoremove }}"
      when:
        - ansible_pkg_mgr == "apt"
        - update_autoremove == "yes"
  when:
    - ansible_pkg_mgr == "apt"
  become: true

- name: Update all software (DNF)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when:
    - ansible_pkg_mgr == "dnf"
  become: true

- name: Update all software (Pacman)
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  when:
    - ansible_pkg_mgr == "pacman"
  become: true
